### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/Galaxy-XSD#2]
Can you add a license to this repository to allow redistribution in other projects (ideally something along the lines of Apache, MIT, BSD, AFL)?

I would like to include these XSD files in [planemo](https://github.com/galaxyproject/planemo) which provides functionality for linting tools.

**Comment by JeanFred** [comment]
Yeah, this was on my todo forever. Weird overlook on my part.

I usually publish everything I do under [MIT](http://opensource.org/licenses/MIT). Would that work for you @lindenb ? 

Actually, I initially forked this from you @jmchilton (in 241c999) − are you ok with MIT too?

**Comment by jmchilton** [comment]
MIT sounds fantastic to me.

**Comment by lindenb** [comment]
MIT  -> ok

again, the current xsd is outdated & cannot validate all the `tools.xml` I found. My personal current interest is to generate a tool.xml from my java applications without copy+paste a description for each option.

**Comment by lindenb** [comment]
@jmchilton oh, and sorry, I missed your name in the contribution list !  :-)

**Comment by jmchilton** [comment]
@lindenb I believe @bgruening has a method or is developing a method to auto-generate tools from JavaDocs (https://github.com/galaxyproject/planemo/issues/69) - I don't know the details but I would ping him on that.

**Comment by JeanFred** [comment]
This is now done. Thanks all for raising this and agreeing on MIT :)

**Comment by jmchilton** [comment]
Awesome, thanks!

**Comment by JeanFred** [comment]
(And fixing the authors − evil, evil copy-pasting between repos)
