### ISSUE TITLE
Transfer to galaxy-project?

### ISSUE THREAD

**Issue by JeanFred** [galaxyproject/Galaxy-XSD#5]
Hey folks,

I developed this a while back (2013!) for myself ; so I was quite happy to hear it was being used in planemo (and is still included in it apparently!).

While I’m happy to keep this around, and to give basic maintenance (as in merging any PR that would come this way), I was wondering whether it would make sense to transfer this repo to the @galaxyproject organisation?

I’m happy either way, so your call :)

Poke @jmchilton.

**Comment by bgruening** [comment]
I think this is a good idea! Thanks @JeanFred! Anything what you need from us to make this happen?

**Comment by JeanFred** [comment]
Thanks @bgruening for the swift answer!

> Anything what you need from us to make this happen?

I have only ever transferred repos to orgs I also managed, so [I checked](https://help.github.com/articles/about-repository-transfers/) − apparently an owner of the org has to accept in the next 24h.

Additionally, you might want to update [the submodule](https://github.com/galaxyproject/planemo/blob/master/.gitmodules) − not sure how well / for how long  redirects would work.

**Comment by bgruening** [comment]
I will care about the planemo module, no worries. Let me know when you will transfer the repo and I will try to get someone to accept it.

Thanks again for this great work!
Bjoern

**Comment by JeanFred** [comment]
> > Anything what you need from us to make this happen?
> 
> I have only ever transferred repos to orgs I also managed, so I checked − apparently an owner of the org has to accept in the next 24h.

Ok, I tried but this was denied − apparently [Users must have admin or owner permissions within the receiving organization before they can transfer a repository that they individually own](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization).

This is slightly annoying… I don’t particularly want to request Admin credentials on galaxyproject (nor have I earned them!). However it sounds like it’s the only way.

Would it be okay to grant me Admin on galaxyproject, the time for me to transfer the repo? Naturally, it’s okay to revoke them once this is done. :)

**Comment by bgruening** [comment]
I will get someone from the main team to look at this. Can you grant me admin permissions on this repo? I'm not sure I'm admin/owner on galaxyproject but I can try to transfer it.
Thanks!

**Comment by JeanFred** [comment]
> I will get someone from the main team to look at this. Can you grant me admin permissions on this repo? I'm not sure I'm admin/owner on galaxyproject but I can try to transfer it.

I was hoping that would be possible − but apparently, user repos can only ever have one owner (me) and [collaborators](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) who have extended permissions (like you do now), but not to transfer stuff.

Thinking more about this, it would also work for me to transfer the repo directly to an owner of galaxyproject, who would then be able to transfer it to the organisation. That would work too, just needs two transfers instead of one (which I assume would be okay for GitHub to follow?)

**Comment by bgruening** [comment]
Oh this seems to be more complicated than expected. Let's get some owner involved :)

ping @martenson @jmchilton

**Comment by martenson** [comment]
Hi @JeanFred @bgruening ,

To my understanding we are interested in moving this under the main org and help maintaining it. I will mention this on our IRC to seek more feedback.

As to the transfer itself if you add me (@martenson) as a collaborator I should be able to transfer it under @galaxyproject.
If not - please transfer it to me directly and I will transfer it further.

Once transferred I will set you up as an external collaborator and give you admin rights on the repository.

Thanks for the nice work on this, it is very helpful @JeanFred 

Martin

**Comment by JeanFred** [comment]
Hey @martenson, thanks for chiming in!

> To my understanding we are interested in moving this under the main org and help maintaining it. I will mention this on our IRC to seek more feedback.

Brilliant. If you’d like more time for feedback in your community, no worries − last thing I want is for this transfer to be controversial :)

> As to the transfer itself if you add me (@martenson) as a collaborator I should be able to transfer it under @galaxyproject.

Done. Let me know how if that works.

> If not - please transfer it to me directly and I will transfer it further.

Yes, sounds like a plan.

> Once transferred I will set you up as an external collaborator and give you admin rights on the repository.

Thanks! I would appreciate that :)

**Comment by martenson** [comment]
@JeanFred seems you were exactly right and I cannot transfer as an collaborator.

Let's give it time until Wednesday and see if there are any concerns, if not let's fall back to the plan B.

**Comment by JeanFred** [comment]
> Let's give it time until Wednesday and see if there are any concerns, if not let's fall back to the plan B.

Ok !

**Comment by martenson** [comment]
There were no concerns, @JeanFred please transfer the repo to me and I will finish the process. Thanks again!

**Comment by JeanFred** [comment]
> There were no concerns, @JeanFred

Great!

>  please transfer the repo to me and I will finish the process. 

All right, that fails because « martenson/Galaxy-XSD already exists ». Can you delete your fork @martenson to make room for it?

(Gosh, I can’t believe how many hoops there are to jump through...)

**Comment by martenson** [comment]
@JeanFred done, lol :D

**Comment by JeanFred** [comment]
And transfer in progress! Waiting for approval

**Comment by martenson** [comment]
done https://github.com/galaxyproject/Galaxy-XSD
you have admin rights @JeanFred and the whole [Galaxy committers group](https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst) has push access

thank you again!

**Comment by JeanFred** [comment]
Thanks @martenson, @bgruening and everyone involved!

**Comment by bgruening** [comment]
Thanks to you @JeanFred! Hope to see in the Galaxy at some time again!

**Comment by jmchilton** [comment]
Thanks all! @bgruening what do you think about a documentation hackathon to update this someday? I wish I could take a week to just spend on this - and to generate the tool documentation from it - it would be a magnificent resource - I just don't think I can justify the time.

**Comment by bgruening** [comment]
@jmchilton great idea. I actually had the plan to work on this at some point as an internal hackathon here in FR - but making it more official this seems great.
